# Generated by Django 5.2 on 2025-04-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
    ]
