# Generated by Django 5.2 on 2025-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('nombrerepresentantelegal', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contasena', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
