# Generated by Django 5.2 on 2025-05-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_producto_creado_por'),
        ('seller', '0003_usuarioform_delete_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioForm',
        ),
    ]
