# Generated by Django 5.1.5 on 2025-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_direccion_cliente_alter_direccion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
