# Generated by Django 5.2 on 2025-05-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_user'),
        ('seller', '0003_usuarioform_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.usuarioform'),
        ),
    ]
