# Generated by Django 5.2 on 2025-05-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_enviado_por'),
        ('seller', '0003_usuarioform_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vendido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='seller.usuarioform'),
        ),
    ]
