# Generated by Django 5.2 on 2025-05-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_producto_enviado_por_and_more'),
        ('seller', '0003_usuarioform_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='seller.usuarioform'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vendido_por',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
