# Generated by Django 5.2 on 2025-05-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_creado_por_alter_producto_vendido_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creado_por',
        ),
    ]
